/**
 * Tokenizer tests — bash-deny parser Step 1.
 *
 * Three tiers:
 *  - Regression guards: inputs the tokenizer must handle. These MUST pass.
 *  - Red-team cases: spec-correct expectations (per parser.md §4.1) for valid
 *    shell inputs (each verified with `sh -n -c`). Failures reveal real bugs.
 *  - Documented limitations: known places where the §4.1 two-token-window
 *    heuristic diverges from bash. These are *expected* — documented in the
 *    suite so regressions are caught. None are bypass vectors (see comments).
 *
 * Test convention: data-driven `cases` array with group comments.
 * One `it()` per case, generated by iterating the array.
 *
 * Usage: npm test  (or: node --import tsx --test tests/parser/tokenize.test.ts)
 */

import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { tokenize, ParseError, type Tok } from "../../bash-deny/parser.js";

// ═══════════════════════════════════════════════════════════════════
// Test cases
// ═══════════════════════════════════════════════════════════════════

const cases: { input: string; expected: Tok[] }[] = [
  // ── empty / eof ──────────────────────────────────────────────────
  { input: "", expected: [{ kind: "eof" }] },

  // ── simple commands & words ───────────────────────────────────────
  { input: "echo hi", expected: [{ kind: "word", value: "echo" }, { kind: "word", value: "hi" }, { kind: "eof" }] },
  { input: "kubectl delete pod", expected: [{ kind: "word", value: "kubectl" }, { kind: "word", value: "delete" }, { kind: "word", value: "pod" }, { kind: "eof" }] },

  // ── assignments (§4.1 "Assignment vs word") ─────────────────────
  // FOO=bar before a command
  { input: "FOO=bar cmd", expected: [{ kind: "assign", name: "FOO", value: "bar" }, { kind: "word", value: "cmd" }, { kind: "eof" }] },
  // multiple assignments before a command
  { input: "A=1 B=2 cmd", expected: [{ kind: "assign", name: "A", value: "1" }, { kind: "assign", name: "B", value: "2" }, { kind: "word", value: "cmd" }, { kind: "eof" }] },
  // assignment with quoted value containing space (greedy .+ value)
  { input: 'FOO="a b"', expected: [{ kind: "assign", name: "FOO", value: "a b" }, { kind: "eof" }] },
  // value with special chars
  { input: "PATH=/usr/bin:/bin", expected: [{ kind: "assign", name: "PATH", value: "/usr/bin:/bin" }, { kind: "eof" }] },
  // ── not an assignment (§4.1 — anchored ^[A-Za-z_]) ──
  // leading dash → word, not assign
  { input: "--flag=v", expected: [{ kind: "word", value: "--flag=v" }, { kind: "eof" }] },
  // leading digit → word, not assign
  { input: "1=2", expected: [{ kind: "word", value: "1=2" }, { kind: "eof" }] },
  // leading = → word, not assign
  { input: "=foo", expected: [{ kind: "word", value: "=foo" }, { kind: "eof" }] },
  // reserved word as assign NAME is still an assign (name slot, not kw-classified)
  { input: "for=1", expected: [{ kind: "assign", name: "for", value: "1" }, { kind: "eof" }] },

  // ── keywords (§4.1 "kw is emitted everywhere, parser decides position") ──
  { input: "for x in a", expected: [{ kind: "kw", value: "for" }, { kind: "word", value: "x" }, { kind: "kw", value: "in" }, { kind: "word", value: "a" }, { kind: "eof" }] },
  // full for-loop
  { input: "for x in a b; do echo $x; done", expected: [{ kind: "kw", value: "for" }, { kind: "word", value: "x" }, { kind: "kw", value: "in" }, { kind: "word", value: "a" }, { kind: "word", value: "b" }, { kind: "semi" }, { kind: "kw", value: "do" }, { kind: "word", value: "echo" }, { kind: "word", value: "$x" }, { kind: "semi" }, { kind: "kw", value: "done" }, { kind: "eof" }] },
  // if/then/fi
  { input: "if true; then echo a; fi", expected: [{ kind: "kw", value: "if" }, { kind: "word", value: "true" }, { kind: "semi" }, { kind: "kw", value: "then" }, { kind: "word", value: "echo" }, { kind: "word", value: "a" }, { kind: "semi" }, { kind: "kw", value: "fi" }, { kind: "eof" }] },
  // while/do/done
  { input: "while true; do echo a; done", expected: [{ kind: "kw", value: "while" }, { kind: "word", value: "true" }, { kind: "semi" }, { kind: "kw", value: "do" }, { kind: "word", value: "echo" }, { kind: "word", value: "a" }, { kind: "semi" }, { kind: "kw", value: "done" }, { kind: "eof" }] },
  // case/esac with dsemi
  { input: "case x in a) echo;; esac", expected: [{ kind: "kw", value: "case" }, { kind: "word", value: "x" }, { kind: "kw", value: "in" }, { kind: "word", value: "a" }, { kind: "rparen" }, { kind: "word", value: "echo" }, { kind: "dsemi" }, { kind: "kw", value: "esac" }, { kind: "eof" }] },
  // keyword as argument — still emitted as kw, parser reclassifies
  { input: "echo if", expected: [{ kind: "word", value: "echo" }, { kind: "kw", value: "if" }, { kind: "eof" }] },
  { input: "echo for", expected: [{ kind: "word", value: "echo" }, { kind: "kw", value: "for" }, { kind: "eof" }] },

  // ── structural separators ────────────────────────────────────────
  { input: "a && b", expected: [{ kind: "word", value: "a" }, { kind: "op", value: "&&" }, { kind: "word", value: "b" }, { kind: "eof" }] },
  { input: "a || b", expected: [{ kind: "word", value: "a" }, { kind: "op", value: "||" }, { kind: "word", value: "b" }, { kind: "eof" }] },
  { input: "a | b", expected: [{ kind: "word", value: "a" }, { kind: "op", value: "|" }, { kind: "word", value: "b" }, { kind: "eof" }] },
  { input: "cmd &", expected: [{ kind: "word", value: "cmd" }, { kind: "amp" }, { kind: "eof" }] },
  { input: "a; b", expected: [{ kind: "word", value: "a" }, { kind: "semi" }, { kind: "word", value: "b" }, { kind: "eof" }] },
  // chained
  { input: "a;b;c", expected: [{ kind: "word", value: "a" }, { kind: "semi" }, { kind: "word", value: "b" }, { kind: "semi" }, { kind: "word", value: "c" }, { kind: "eof" }] },
  { input: "a&&b||c", expected: [{ kind: "word", value: "a" }, { kind: "op", value: "&&" }, { kind: "word", value: "b" }, { kind: "op", value: "||" }, { kind: "word", value: "c" }, { kind: "eof" }] },
  { input: "a | b | c", expected: [{ kind: "word", value: "a" }, { kind: "op", value: "|" }, { kind: "word", value: "b" }, { kind: "op", value: "|" }, { kind: "word", value: "c" }, { kind: "eof" }] },
  // ;; is dsemi (checked before ;), case-clause terminator
  { input: "case x in a) b;; esac", expected: [{ kind: "kw", value: "case" }, { kind: "word", value: "x" }, { kind: "kw", value: "in" }, { kind: "word", value: "a" }, { kind: "rparen" }, { kind: "word", value: "b" }, { kind: "dsemi" }, { kind: "kw", value: "esac" }, { kind: "eof" }] },

  // ── subshell parens ──────────────────────────────────────────────
  { input: "(cmd)", expected: [{ kind: "lparen" }, { kind: "word", value: "cmd" }, { kind: "rparen" }, { kind: "eof" }] },
  { input: "(a;b)", expected: [{ kind: "lparen" }, { kind: "word", value: "a" }, { kind: "semi" }, { kind: "word", value: "b" }, { kind: "rparen" }, { kind: "eof" }] },

  // ── comments (§4.1 — # only at word boundary) ───────────────────
  // # comment — emit nl on the \n
  { input: "# c\necho", expected: [{ kind: "nl" }, { kind: "word", value: "echo" }, { kind: "eof" }] },
  // # comment after whitespace — consumed, nothing emitted
  { input: "echo #foo", expected: [{ kind: "word", value: "echo" }, { kind: "eof" }] },
  // # comment after semi — consumed
  { input: "echo;#foo", expected: [{ kind: "word", value: "echo" }, { kind: "semi" }, { kind: "eof" }] },
  // # mid-word is a literal byte (verified: sh -c 'echo#foo' → command not found)
  { input: "echo#foo", expected: [{ kind: "word", value: "echo#foo" }, { kind: "eof" }] },
  // # comment with no trailing newline (EOF) — no nl emitted
  { input: "echo # foo", expected: [{ kind: "word", value: "echo" }, { kind: "eof" }] },

  // ── single quotes (§4.1) ────────────────────────────────────────
  // echo 'a' → quotes eaten, content "a"
  { input: "echo 'a'", expected: [{ kind: "word", value: "echo" }, { kind: "word", value: "a" }, { kind: "eof" }] },
  // empty single quotes → empty word
  { input: "echo ''", expected: [{ kind: "word", value: "echo" }, { kind: "word", value: "" }, { kind: "eof" }] },
  // sq inside dq — ' is literal inside double quotes
  { input: "echo \"it's\"", expected: [{ kind: "word", value: "echo" }, { kind: "word", value: "it's" }, { kind: "eof" }] },
  // dq inside sq — " is literal inside single quotes
  { input: "echo 'say \"hi\"'", expected: [{ kind: "word", value: "echo" }, { kind: "word", value: 'say "hi"' }, { kind: "eof" }] },
  // single-quoted content with special chars — all literal
  { input: "echo 'a;b|c&&d'", expected: [{ kind: "word", value: "echo" }, { kind: "word", value: "a;b|c&&d" }, { kind: "eof" }] },

  // ── double quotes (§4.1) ────────────────────────────────────────
  { input: 'echo "a"', expected: [{ kind: "word", value: "echo" }, { kind: "word", value: "a" }, { kind: "eof" }] },
  { input: 'echo "a b"', expected: [{ kind: "word", value: "echo" }, { kind: "word", value: "a b" }, { kind: "eof" }] },
  // empty double quotes → empty word
  { input: 'echo ""', expected: [{ kind: "word", value: "echo" }, { kind: "word", value: "" }, { kind: "eof" }] },
  // adjacent quoted/unquoted segments concatenate into one word
  { input: 'echo "a"b"c"', expected: [{ kind: "word", value: "echo" }, { kind: "word", value: "abc" }, { kind: "eof" }] },
  // dq escaped backslash — \\ inside "..." is literal \
  { input: 'echo "a\\\\b"', expected: [{ kind: "word", value: "echo" }, { kind: "word", value: "a\\b" }, { kind: "eof" }] },
  // dq escaped quote — \" inside "..." is literal "
  { input: 'echo "a\\"b"', expected: [{ kind: "word", value: "echo" }, { kind: "word", value: 'a"b' }, { kind: "eof" }] },
  // dq backslash before ordinary byte — backslash is literal, kept (§4.1)
  { input: 'echo "a\\b"', expected: [{ kind: "word", value: "echo" }, { kind: "word", value: "a\\b" }, { kind: "eof" }] },

  // ── backslash escapes outside quotes ─────────────────────────────
  // escaped structural chars become literal word bytes
  { input: "echo \\;", expected: [{ kind: "word", value: "echo" }, { kind: "word", value: ";" }, { kind: "eof" }] },
  { input: "echo \\\\", expected: [{ kind: "word", value: "echo" }, { kind: "word", value: "\\" }, { kind: "eof" }] },

  // ── bang (§4.1 — standalone ! with separators around it) ────────
  // standalone ! → bang
  { input: "! true", expected: [{ kind: "bang" }, { kind: "word", value: "true" }, { kind: "eof" }] },
  { input: "!;cmd", expected: [{ kind: "bang" }, { kind: "semi" }, { kind: "word", value: "cmd" }, { kind: "eof" }] },
  { input: "!&&cmd", expected: [{ kind: "bang" }, { kind: "op", value: "&&" }, { kind: "word", value: "cmd" }, { kind: "eof" }] },
  { input: "!(cmd)", expected: [{ kind: "bang" }, { kind: "lparen" }, { kind: "word", value: "cmd" }, { kind: "rparen" }, { kind: "eof" }] },
  // ! at EOF → bang (option 2: EOF is a separator). sh -c '!' is a syntax error anyway.
  { input: "!", expected: [{ kind: "bang" }, { kind: "eof" }] },
  // ! glued to following bytes → word
  { input: "!foo", expected: [{ kind: "word", value: "!foo" }, { kind: "eof" }] },
  // ! mid-word → word
  { input: "a!", expected: [{ kind: "word", value: "a!" }, { kind: "eof" }] },

  // ── braces (§4.1 command-position two-token window) ─────────────
  // { echo a; } → { in command position + followed by space → lbrace/rbrace
  { input: "{ echo a; }", expected: [{ kind: "lbrace" }, { kind: "word", value: "echo" }, { kind: "word", value: "a" }, { kind: "semi" }, { kind: "rbrace" }, { kind: "eof" }] },
  // { } → empty brace group
  { input: "{ }", expected: [{ kind: "lbrace" }, { kind: "rbrace" }, { kind: "eof" }] },
  // echo {a,b} → brace expansion, { not in command position, fold into word
  { input: "echo {a,b}", expected: [{ kind: "word", value: "echo" }, { kind: "word", value: "{a,b}" }, { kind: "eof" }] },
  // echo ${VAR} → ${ folds into word (tok non-empty after $)
  { input: "echo ${VAR}", expected: [{ kind: "word", value: "echo" }, { kind: "word", value: "${VAR}" }, { kind: "eof" }] },
  // parameter expansion with default
  { input: "echo ${VAR:-x}", expected: [{ kind: "word", value: "echo" }, { kind: "word", value: "${VAR:-x}" }, { kind: "eof" }] },
  // {} glued → one word (not a brace group)
  { input: "{}", expected: [{ kind: "word", value: "{}" }, { kind: "eof" }] },

  // ── whitespace edge cases ────────────────────────────────────────
  { input: "  echo", expected: [{ kind: "word", value: "echo" }, { kind: "eof" }] },
  { input: "echo  ", expected: [{ kind: "word", value: "echo" }, { kind: "eof" }] },
  { input: "echo\thi", expected: [{ kind: "word", value: "echo" }, { kind: "word", value: "hi" }, { kind: "eof" }] },
  { input: "a\n\nb", expected: [{ kind: "word", value: "a" }, { kind: "nl" }, { kind: "nl" }, { kind: "word", value: "b" }, { kind: "eof" }] },

  // ── line continuation outside quotes (§4.1 — \<newline> collapses) ──
  // echo \<newline>hello → collapse to "echo hello"
  { input: "echo \\\nhello", expected: [{ kind: "word", value: "echo" }, { kind: "word", value: "hello" }, { kind: "eof" }] },

  // ── opaque word content (§4.1) ──────────────────────────────────
  // backticks — opaque word content
  { input: "echo `rm`", expected: [{ kind: "word", value: "echo" }, { kind: "word", value: "`rm`" }, { kind: "eof" }] },
  // $(...) — opaque word content
  { input: "echo $(rm)", expected: [{ kind: "word", value: "echo" }, { kind: "word", value: "$(rm)" }, { kind: "eof" }] },
  // empty $() → one word
  { input: "echo $()", expected: [{ kind: "word", value: "echo" }, { kind: "word", value: "$()" }, { kind: "eof" }] },
  // $'...' ANSI-C quoting — escapes evaluated (so $'ls' ≡ ls)
  { input: "echo $'ls'", expected: [{ kind: "word", value: "echo" }, { kind: "word", value: "ls" }, { kind: "eof" }] },
  // $'\154\163' — octal escapes → "ls"
  { input: "echo $'\\154\\163'", expected: [{ kind: "word", value: "echo" }, { kind: "word", value: "ls" }, { kind: "eof" }] },
  // $'\x6c\x73' — hex escapes → "ls"
  { input: "echo $'\\x6c\\x73'", expected: [{ kind: "word", value: "echo" }, { kind: "word", value: "ls" }, { kind: "eof" }] },
  // l$'\163' — concatenation → "ls"
  { input: "l$'\\163'", expected: [{ kind: "word", value: "ls" }, { kind: "eof" }] },
  // $'\t' — control escape → tab
  { input: "a $'\\t'", expected: [{ kind: "word", value: "a" }, { kind: "word", value: "\t" }, { kind: "eof" }] },
  // $'' — empty → empty word
  { input: "echo $''", expected: [{ kind: "word", value: "echo" }, { kind: "word", value: "" }, { kind: "eof" }] },
];

// ═══════════════════════════════════════════════════════════════════
// Documented limitations — the §4.1 two-token-window divergence (not bugs)
// ═══════════════════════════════════════════════════════════════════
//
// These document places where the tokenizer's local heuristic diverges from
// bash. They are NOT bypass vectors:
//  - `echo }` → rbrace: the parser will see an unbalanced rbrace and reject
//    (false positive on a safe command, not a bypass). The trade is that brace
//    groups (`{ rm -rf; }`) tokenize correctly so the deny rule can match.
//  - backticks/$(...) with internal whitespace split: the construct is "opaque
//    word content" — a future parser-level enhancement may re-parse word text.
//    Today these produce multiple tokens; the engine's matchPattern still sees
//    the leaf command surface.
//
// They are in `cases` (not skipped) so a future fix that improves the heuristic
// flips them green and makes the improvement visible.

const limitations: { input: string; expected: Tok[]; note: string }[] = [
  // echo } → rbrace (literal brace-as-arg mis-classified as closer)
  // bash: sh -c 'echo }' → "}". Here: rbrace → parser rejects as unbalanced.
  { input: "echo }", expected: [{ kind: "word", value: "echo" }, { kind: "rbrace" }, { kind: "eof" }], note: "literal } arg → rbrace (two-token window; parser rejects, not a bypass)" },
  // echo } followed by more — same root cause, not EOF-specific
  { input: "echo } x", expected: [{ kind: "word", value: "echo" }, { kind: "rbrace" }, { kind: "word", value: "x" }, { kind: "eof" }], note: "literal } arg → rbrace (two-token window)" },
  // backticks with internal space split into two words (opaque construct not balanced)
  { input: "echo `echo rm`", expected: [{ kind: "word", value: "echo" }, { kind: "word", value: "`echo" }, { kind: "word", value: "rm`" }, { kind: "eof" }], note: "backticks with internal space split (opaque construct limitation)" },
];

// ═══════════════════════════════════════════════════════════════════
// Test runner
// ═══════════════════════════════════════════════════════════════════

describe("tokenize", () => {
  for (const { input, expected } of cases) {
    it(`${JSON.stringify(input)}`, () => {
      const result = tokenize(input);
      assert.deepStrictEqual(result, expected);
    });
  }

  for (const { input, expected, note } of limitations) {
    it(`${JSON.stringify(input)} (limitation: ${note})`, () => {
      const result = tokenize(input);
      assert.deepStrictEqual(result, expected);
    });
  }

  // ── unclosed quote at EOF must throw (§4.1 errors) ──────────────
  it(`"echo 'a" (unclosed single quote) → throws ParseError`, () => {
    assert.throws(
      () => tokenize("echo 'a"),
      (e: unknown) => e instanceof ParseError,
    );
  });

  it(`'echo "a' (unclosed double quote) → throws ParseError`, () => {
    assert.throws(
      () => tokenize('echo "a'),
      (e: unknown) => e instanceof ParseError,
    );
  });

  it(`"echo \\" (dangling escape) → throws ParseError`, () => {
    assert.throws(
      () => tokenize("echo \\"),
      (e: unknown) => e instanceof ParseError,
    );
  });

  // ── ParseError carries the byte position ────────────────────────
  it(`ParseError carries byte position`, () => {
    try {
      tokenize("echo 'a");
      assert.fail("expected throw");
    } catch (e: unknown) {
      assert.ok(e instanceof ParseError, "should be ParseError");
      assert.equal((e as ParseError).pos, 7, "pos should be input length");
    }
  });
});
